Lasso filter
NSAPH-Software/CRE pull request #75
Opened 2022-10-19 04:51 UTC by riccardocadei

Fix Stability Selection LASSO filter.
Replace `q` with `cutoff`.

Closes #74

2022-10-19 05:13 UTC, riccardocadei commented
@Naeemkh do you know if there is an automatic way to fix this check error? (anyway I cannot understand which file is not updated)

2022-10-24 12:36 UTC, Naeemkh commented
@riccardocadei, please resolve conflicts and make sure the tests pass.

2022-10-24 22:01 UTC, Naeemkh requested changes

2022-10-24 22:38 UTC, riccardocadei commented on R/lasso_rules_filter.R
> +                                    alpha = 1,
It is on purpose because we want to use LASSO which corresponds to cv.glmnet (family of model) with alpha=1.

2022-10-24 22:40 UTC, riccardocadei commented on R/cre.R
> +
What do you mean? all the other values of M are computed before, but M["Filter 5 (CATE)"] can computed only here, after the CATE estimation

2022-10-24 22:43 UTC, riccardocadei commented on R/extract_rules.R
> +                                digits = 2)
it corresponds to the number of digits per rounding. Do you want to add it as hyper_param?

2022-10-24 22:44 UTC, riccardocadei commented on tests/testthat/test-prune_rules.R
> +  expect_equal(rules_RF[3], "X[,3]<=0.5 & X[,8]>0.39 & X[,9]>0.1")
ok

2022-10-25 12:24 UTC, Naeemkh commented on R/cre.R
> +
If this is part of the output, we need to include it's details in the `return` section of documentation.

2022-10-25 12:25 UTC, Naeemkh commented on R/extract_rules.R
> +                                digits = 2)
No. Please add what is it to line 12 in the documentation, then run document().

2022-10-25 13:18 UTC, riccardocadei commented on R/cre.R
> +
it is returned inside cre_result.M (which is already present in the CRAN submission)
which documentation should I update?

2022-10-25 13:23 UTC, riccardocadei commented on R/extract_rules.R
> +                                digits = 2)
Fixed.

2022-10-25 15:58 UTC, Naeemkh approved these changes

2022-10-25 15:59 UTC, merged