Individual Treatment Effect
NSAPH-Software/CRE pull request #97
Opened 2023-01-11 07:16 UTC by riccardocadei

Significantly modify ITE estimators (both methods and function).

Added:
- S-Learner (`slearner`) method for ITE estimation  (fix Issue #96).
- T-Learner (`tlearner`) method for ITE estimation  (fix Issue #96).
- X-Learner (`xlearner`) method for ITE estimation  (fix Issue #96).

Rename:
- `offset` method-parameter -> hyper-parameter.
- `estimate_ite_poisson` function -> `estimate_ite_tpoisson`  (fix Issue #96).

Discard: 
- `include_ps_inf` method-parameter.
- `include_ps_dis` method-parameter.
- `oreg` method for ITE estimation.
- `ipw` method for ITE estimation (fix Issue #95).
- `sipw` method for ITE estimation (fix Issue #95).
- ITE standard deviation estimation.

Clean and discard many useless internal parameters for ITE estimation.

2023-01-17 22:15 UTC, Naeemkh requested changes
Thanks, @riccardocadei :

- Please see my comments (mostly on styling).
- Please add a note section to the CRE package and direct the users to read more about S-, T-, and X-Learners.
- In the CRE parameters, for `replace`, please add more details. Replacing what and where in the process. 
- Do you have any example using `interventional_vars` in the CRE function? It does not show up in the default parameters. 
- CRE function documentation and default values (for cutoff and pfer) are not consistent. Please double-check.

2023-01-17 23:33 UTC, riccardocadei commented on NEWS.md
> +* Rules Generation Issue.
See Issue #91.

2023-01-17 23:38 UTC, riccardocadei commented on R/filter_irrelevant_rules.R
> +      rules[i] <- sub("<=", ">", rules[i])
yes, since we are considering only rules with lengths==1 .

2023-01-17 23:42 UTC, riccardocadei commented on vignettes/CRE.Rmd
>  **`method_parameters`** The list of parameters to define the models used, including:
between 47 and 48?

2023-01-17 23:58 UTC, Naeemkh commented on NEWS.md
> +* Rules Generation Issue.
It should be clear to the users, too.

2023-01-18 00:10 UTC, riccardocadei commented
CRE function documentation and default values (for cutoff and pfer) seems consistent to me:
pfer = 1, cutoff = 0.9.
Am I missing something?

2023-01-18 00:13 UTC, Naeemkh commented
> 

In the default values, it is the other way around:
pfer = 0.9, cutoff = 1.

2023-01-18 00:28 UTC, riccardocadei commented
great catch on the default values!

I think I have addressed all your comments. Except leaving a reference for the *-learners. I think they are already well-known in the literature, and if not, we will leave the proper references in the main paper (and software paper) if necessary.
I don't see why adding a reference for them, not others.

2023-01-18 00:32 UTC, Naeemkh commented
> great catch on the default values!
> 
> I think I have addressed all your comments. Except leaving a reference for the *-learners. I think they are already well-known in the literature, and if not, we will leave the proper references in the main paper (and software paper) if necessary. I don't see why adding a reference for them, not others.

That is fine; we can skip the reference. To answer your question, we use their packages for other methods, but for these three approaches, we code them.

2023-01-18 00:43 UTC, merged